Command.Deploy: add checkSystemKnownHosts option to ob deploy init #569
obsidiansystems/obelisk pull request #916
Opened 2022-05-09 18:39 UTC by romefeller

This PR is the new version of PR 569.

https://github.com/obsidiansystems/obelisk/pull/569/

2022-05-11 17:47 UTC, madeline-os requested changes
Comment fixes requested

2022-05-11 17:47 UTC, madeline-os commented on lib/command/src/Obelisk/Command.hs
> +thunkDirectoryParser :: Parser FilePath
Please add a haddock and remove this TODO. make an issue for it after we merge this PR

2022-05-11 17:47 UTC, madeline-os commented on lib/command/src/Obelisk/Command/Deploy.hs
> +lookupKnownHosts :: MonadObelisk m  => String -> m [BS.ByteString]
Haddock

2022-05-11 17:47 UTC, madeline-os commented on lib/command/src/Obelisk/Command/Deploy.hs
> +addKnownHostFromEnv :: MonadObelisk m => String -> FilePath -> m ()
Haddock

2022-05-11 18:21 UTC, romefeller commented on lib/command/src/Obelisk/Command/Deploy.hs
> +addKnownHostFromEnv :: MonadObelisk m => String -> FilePath -> m ()
Done

2022-05-11 18:34 UTC, madeline-os approved these changes

2022-05-11 18:57 UTC, merged

2022-05-23 14:55 UTC, alexfmpe commented on lib/command/src/Obelisk/Command/Deploy.hs
> +  fmap filterComments $ readCreateProcessWithExitCode $ proc "ssh-keygen" ["-F", hostName]
https://github.com/obsidiansystems/obelisk/pull/569#discussion_r357864129

2022-05-23 14:56 UTC, madeline-os commented on lib/command/src/Obelisk/Command/Deploy.hs
> +  fmap filterComments $ readCreateProcessWithExitCode $ proc "ssh-keygen" ["-F", hostName]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2022-05-23 14:57 UTC, madeline-os commented on lib/command/src/Obelisk/Command/Deploy.hs
> +  fmap filterComments $ readCreateProcessWithExitCode $ proc "ssh-keygen" ["-F", hostName]
thank yo ualex