Fix knownHost using staticWithNix
obsidiansystems/obelisk pull request #931
Opened 2022-05-23 23:26 UTC by romefeller

I have:

  - [x] Based work on latest `develop` branch
  - [x] Followed the [contribution guide](https://github.com/obsidiansystems/obelisk/blob/develop/CONTRIBUTING.md#submitting-changes)
  - [x] Looked for lint in my changes with `hlint .` (lint found code you did not write can be left alone)
  - [ ] Run the test suite: `$(nix-build -A selftest --no-out-link)`
  - [ ] [Updated the changelog](https://github.com/obsidiansystems/obelisk/blob/develop/CONTRIBUTING.md#in-the-changelog)
  - [ ] (Optional) Run CI tests locally: `nix-build release.nix -A build.x86_64-linux --no-out-link` (or `x86_64-darwin` on macOS)

2022-05-24 05:02 UTC, madeline-os approved these changes

2022-05-24 05:03 UTC, madeline-os requested changes
Actually, I think we need a test for this. It should cover the original feature, and ensures that it operates as expected. This might be a little tricky. If it's not clear how to proceed, let's talk about it.

2022-05-24 21:08 UTC, romefeller commented
> @romefeller I don't think we have `deploy` tests yet so nevermind. i would like for you to verify that it works on an EC2 deploy before we merge, tho.

@madeline-os ok.

2022-06-14 18:20 UTC, madeline-os approved these changes

2022-06-14 18:20 UTC, merged